# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0002_quota'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quotas',
            field=models.ManyToManyField(blank=True, related_name='students', to='handbooks.quota', verbose_name='Квоты'),
        ),
    ]
