# Generated by Django 5.2.4 on 2025-07-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование квалификации')),
                ('is_worker_qualification', models.BooleanField(default=False, verbose_name='Рабочая квалификация')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='handbooks.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
    ]
