# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование квоты')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
            },
        ),
    ]
