# Generated by Django 5.2.4 on 2025-07-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('qualification', models.CharField(choices=[('Техник', 'Техник'), ('Прикладной бакалавр', 'Прикладной бакалавр')], max_length=50, verbose_name='Квалификация')),
                ('study_form', models.CharField(choices=[('Очная', 'Очная'), ('Заочная', 'Заочная')], max_length=50, verbose_name='Форма обучения')),
                ('base_education', models.CharField(choices=[('9 классов', '9 классов'), ('11 классов', '11 классов'), ('ТиПО', 'ТиПО')], max_length=50, verbose_name='На базе')),
                ('school', models.CharField(max_length=255, verbose_name='Школа/Колледж')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания')),
                ('with_honors', models.BooleanField(default=False, verbose_name='С отличием')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Средний балл аттестата')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('study_language', models.CharField(max_length=50, verbose_name='Язык обучения')),
                ('social_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Социальный статус')),
                ('citizenship', models.CharField(default='Республика Казахстан', max_length=100, verbose_name='Гражданство')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальность')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Контакты')),
                ('home_address', models.CharField(max_length=255, verbose_name='Дом. адрес')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплатили')),
                ('parents_info', models.TextField(blank=True, null=True, verbose_name='ФИО родителей')),
                ('has_incomplete_docs', models.BooleanField(default=False, verbose_name='Неполный пакет документов')),
                ('needs_dormitory', models.BooleanField(default=False, verbose_name='Общежитие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
