# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('handbooks', '0002_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='quotas',
            field=models.ManyToManyField(blank=True, related_name='abiturients', to='handbooks.quota', verbose_name='Квоты'),
        ),
    ]
