# Generated by Django 5.2.4 on 2025-07-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование квалификации')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='enrollment.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.qualification', verbose_name='Квалификация'),
        ),
    ]
