# Generated by Django 5.2.4 on 2025-07-21 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_qualification_alter_applicant_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='payment_type',
            field=models.CharField(choices=[('Госзаказ', 'Госзаказ'), ('Платное', 'Платное')], default='Платное', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер приказа')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан')], default='draft', max_length=10, verbose_name='Статус')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants', models.ManyToManyField(related_name='orders', to='enrollment.applicant', verbose_name='Абитуриенты в приказе')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан (Editor)')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем подписан (Admin)')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
    ]
