# Generated by Django 5.2.4 on 2025-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_applicant_payment_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='study_form',
            field=models.CharField(choices=[('Очная', 'Очная'), ('Дуальное', 'Дуальное')], max_length=50, verbose_name='Форма обучения'),
        ),
    ]
