# Generated by Django 5.2.4 on 2025-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_applicant_study_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], default='Не оплачено', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_type',
            field=models.CharField(choices=[('Госзаказ', 'Госзаказ'), ('Платное', 'Платное')], default='Платное', max_length=20, verbose_name='Тип финансирования'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='study_form',
            field=models.CharField(choices=[('Очная', 'Очная'), ('Заочная', 'Заочная')], max_length=50, verbose_name='Форма обучения'),
        ),
    ]
