# Generated by Django 5.2.4 on 2025-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_remove_applicant_is_paid_applicant_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='study_form',
            field=models.CharField(choices=[('Очная', 'Очная'), ('Дуальная', 'Дуальная')], max_length=50, verbose_name='Форма обучения'),
        ),
    ]
