# Generated by Django 5.2.4 on 2025-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_applicant_study_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='base_education',
            field=models.CharField(blank=True, choices=[('9 классов', '9 классов'), ('11 классов', '11 классов'), ('ТиПО', 'ТиПО')], max_length=50, null=True, verbose_name='На базе'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, default='Республика Казахстан', max_length=100, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Средний балл аттестата'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом. адрес'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], default='Не оплачено', max_length=20, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Госзаказ', 'Госзаказ'), ('Платное', 'Платное')], default='Платное', max_length=20, null=True, verbose_name='Тип финансирования'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа/Колледж'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='study_form',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Заочная', 'Заочная')], max_length=50, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='study_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык обучения'),
        ),
    ]
