# Generated by Django 5.2.4 on 2025-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_alter_applicant_base_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='study_form',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Дуальная', 'Дуальная')], max_length=50, null=True, verbose_name='Форма обучения'),
        ),
    ]
