# Generated by Django 5.2.4 on 2025-07-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_applicant_application_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preamble',
            field=models.TextField(blank=True, null=True, verbose_name='Преамбула (основание)'),
        ),
        migrations.AddField(
            model_name='order',
            name='signer_title',
            field=models.CharField(default='Директор колледжа', max_length=255, verbose_name='Должность подписанта'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Приказ о зачислении', max_length=500, verbose_name='Заголовок приказа'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='Код специальности'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_worker_specialty',
            field=models.BooleanField(default=False, verbose_name='Рабочая специальность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем подписан'),
        ),
    ]
