# Generated by Django 5.2.4 on 2025-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_order_preamble_order_signer_title_order_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='is_worker_specialty',
        ),
        migrations.AddField(
            model_name='qualification',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='Код специальности'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_worker_qualification',
            field=models.BooleanField(default=False, verbose_name='Рабочая квалификация'),
        ),
    ]
