# Generated by Django 5.2.4 on 2025-07-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_remove_specialty_is_worker_specialty_and_more'),
        ('handbooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbooks.qualification', verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbooks.qualification', verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbooks.specialty', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbooks.specialty', verbose_name='Специальность'),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
