# Generated by Django 5.2.4 on 2025-07-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_alter_applicant_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='signed_by',
        ),
    ]
