# Generated by Django 5.2.4 on 2025-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_remove_order_applicants_remove_order_created_by_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='movement_history',
            field=models.ManyToManyField(blank=True, to='orders.order', verbose_name='История приказов'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
