# Generated by Django 5.2.4 on 2025-07-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_alter_student_movement_history_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
